[project]
name = "arxiv-crawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.16",
    "beautifulsoup4>=4.13.3",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "rich>=14.0.0",
]
